version: "3"

services:

  podverse_nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: podverse_nginx_proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  podverse_db:
    image: postgres
    container_name: podverse_db
    env_file:
      - ./config/podverse-db.env
    ports:
      - '5432:5432'

  # podverse_api_seed_db:
  #   image: podverse/podverse_api
  #   env_file:
  #     - ./config/podverse-api.env
  #   depends_on:
  #     - podverse_db
  #   command: npm run seeds:categories | npm run seeds:podcasts

  podverse_api:
    image: podverse/podverse_api:1.0.0
    container_name: podverse_api
    env_file:
      - ./config/podverse-api.env
    environment:
      VIRTUAL_HOST: api.stage.podverse.fm
      VIRTUAL_PORT: 1234
    expose:
      - 80
      - 1234
    ports:
      - '1234:80'
    depends_on:
      - podverse_db
    command: npm start
    volumes:
      - ./config/google/jwt.keys.json:/tmp/src/config/google/jwt.keys.json
      - ./config/bitpay/api.key:/tmp/src/config/bitpay/api.key

  podverse_web:
    image: podverse/podverse_web:2.0.0
    container_name: podverse_web
    build: .
    env_file:
      - ./config/podverse-web.env
    environment:
      VIRTUAL_HOST: stage.podverse.fm
      VIRTUAL_PORT: 8765
    expose:
      - 80
      - 8765
    ports:
      - '8765:80'
    depends_on:
      - podverse_db
      - podverse_api
    command: npm start

networks:
  default:
    external:
      name: nginx-proxy
