version: "2"

networks:
  nginx-proxy:
    external: true

services:
  podverse_db:
    image: postgres:11.5
    container_name: podverse_db_local
    env_file:
      - ./config/podverse-db-local.env
    ports:
      - '5432:5432'
    networks:
      - nginx-proxy
    # volumes:
    #   - /Volumes/PODVERSE2/postgresql/data:/var/lib/postgresql/data
    command: postgres -c max_connections=200 -c superuser_reserved_connections=20 -c shared_buffers=2GB -c effective_cache_size=6GB -c maintenance_work_mem=512MB -c checkpoint_completion_target=0.7 -c wal_buffers=16MB -c default_statistics_target=100 -c random_page_cost=1.1 -c effective_io_concurrency=200 -c work_mem=5242kB -c min_wal_size=1GB -c max_wal_size=2GB -c max_worker_processes=4 -c max_parallel_workers_per_gather=2 -c max_parallel_workers=4
    restart: always
    shm_size: 1gb
    logging:
      driver: 'json-file'
      options:
        max-file: '1'
        max-size: '50m'
    
  podverse_manticore:
    image: manticoresearch/manticore
    container_name: podverse_manticore_local
    depends_on: 
      - podverse_db
    restart: always
    networks:
      - nginx-proxy
    ports:
      - 9306:9306
      - 9308:9308
    deploy:
      resources:
        limits:
          memory: 4GB
    ulimits:
      nproc: 65535
      nofile:
         soft: 65535
         hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./manticore/data:/var/lib/manticore
      - ./manticore/episode_export_csvs/episode_export_00.csv:/etc/manticoresearch/episode_export_00.csv
      - ./manticore/episode_export_csvs/episode_export_01.csv:/etc/manticoresearch/episode_export_01.csv
      - ./manticore/episode_export_csvs/episode_export_02.csv:/etc/manticoresearch/episode_export_02.csv
      - ./manticore/episode_export_csvs/episode_export_03.csv:/etc/manticoresearch/episode_export_03.csv
      - ./manticore/episode_export_csvs/episode_export_04.csv:/etc/manticoresearch/episode_export_04.csv
      - ./manticore/episode_export_csvs/episode_export_05.csv:/etc/manticoresearch/episode_export_05.csv
      - ./manticore/episode_export_csvs/episode_export_06.csv:/etc/manticoresearch/episode_export_06.csv
      - ./manticore/episode_export_csvs/episode_export_07.csv:/etc/manticoresearch/episode_export_07.csv
      - ./manticore/episode_export_csvs/episode_export_08.csv:/etc/manticoresearch/episode_export_08.csv
      - ./manticore/episode_export_csvs/episode_export_09.csv:/etc/manticoresearch/episode_export_09.csv
      - ./manticore/episode_export_csvs/episode_export_10.csv:/etc/manticoresearch/episode_export_10.csv
      - ./manticore/episode_export_csvs/episode_export_11.csv:/etc/manticoresearch/episode_export_11.csv
      - ./manticore/episode_export_csvs/episode_export_12.csv:/etc/manticoresearch/episode_export_12.csv
      - ./manticore/episode_export_csvs/episode_export_13.csv:/etc/manticoresearch/episode_export_13.csv
      - ./manticore/episode_export_csvs/episode_export_14.csv:/etc/manticoresearch/episode_export_14.csv
      - ./manticore/episode_export_csvs/episode_export_15.csv:/etc/manticoresearch/episode_export_15.csv
      - ./manticore/episode_export_csvs/episode_export_16.csv:/etc/manticoresearch/episode_export_16.csv
      - ./manticore/episode_export_csvs/episode_export_17.csv:/etc/manticoresearch/episode_export_17.csv
      - ./manticore/episode_export_csvs/episode_export_18.csv:/etc/manticoresearch/episode_export_18.csv
      - ./manticore/episode_export_csvs/episode_export_19.csv:/etc/manticoresearch/episode_export_19.csv
      - ./manticore/manticore.conf:/etc/manticoresearch/manticore.conf
    logging:
      driver: 'json-file'
      options:
        max-file: '1'
        max-size: '50m'

  # podverse_api:
  #   image: podverse_api
  #   container_name: podverse_api_local
  #   env_file:
  #     - ./config/podverse-api-local.env
  #   ports:
  #     - '1234:1234'
  #   volumes:
  #     - ./config/google/jwt.keys.json:/tmp/src/config/google/jwt.keys.json
  #   command: npm start

  # podverse_api_parser_worker:
  #   image: podverse_api
  #   container_name: podverse_api_parser_worker_local
  #   env_file:
  #     - ./config/podverse-api-local.env

  # podverse_api_stats:
  #   image: podverse_api
  #   container_name: podverse_api_stats_local
  #   env_file:
  #     - ./config/podverse-api-local.env
  #   volumes:
  #     - ./config/google/jwt.keys.json:/tmp/src/config/google/jwt.keys.json

  # podverse_web:
  #   image: podverse_web
  #   container_name: podverse_web_local
  #   env_file:
  #     - ./config/podverse-web-local.env
  #   ports:
  #     - '3000:3000'
  #   command: npm start
