version: "2"

services:

  podverse_nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: podverse_nginx_proxy_stage
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  podverse_db:
    image: postgres
    container_name: podverse_db_local
    env_file:
      - ./config/podverse-db-local.env
    ports:
      - '5432:5432'

  podverse_api:
    image: podverse_api
    container_name: podverse_api_local
    depends_on:
      - podverse_db
    env_file:
      - ./config/podverse-api-local.env
    ports:
      - '1234:1234'
    volumes:
      - ./config/bitpay/api.key:/tmp/src/config/bitpay/api.key
      - ./config/google/jwt.keys.json:/tmp/src/config/google/jwt.keys.json
    command: tail -f /dev/null

  podverse_web:
    image: podverse_web
    container_name: podverse_web_local
    depends_on:
      - podverse_db
      - podverse_api
    env_file:
      - ./config/podverse-web-local.env
    ports:
      - '8765:8765'
    command: tail -f /dev/null

networks:
  default:
    driver: bridge
