version: "3"
services:

  # podverse_web:
  #   # image: podverse/podverse-web
  #   image: podverse_web
  #   ports: 
  #     - 8765:8080
  #   env_file:
  #     - ./config/podverse-web.env
  #   depends_on: 
  #     - podverse_db

  # podverse_admin:
  #   image: podverse/podverse_admin
  #   ports: 8000:8000
  #   env_file:
  #     - podverse-admin-variables.env

  podcast_db:
    # image: podverse/podcast_db
    image: podcast_db
    env_file:
      - ./config/podcast-db.env
    command: /tmp/scripts/test.js

  podverse_db:
    image: postgres
    env_file:
      - ./config/podverse-db.env  
    # volumes:
    #    - db-data:/mnt/podversedbvolume1 (env var goes here)

  podcast_db_test:
    # image: podverse/podcast_db
    image: podcast_db
    env_file:
      - ./config/podcast-db-test.env
    command: /tmp/scripts/test.js
    depends_on:
      - podverse_db_test

  podverse_db_test:
    image: postgres
    command: -p 4443
    env_file:
      - ./config/podverse-db-test.env  