version: "3"

services:

  podverse_nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: podverse_nginx_proxy_prod
    ports:
      - 80:80
      - 443:443
    volumes:      
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /home/user/tools/nginx_webproxy/certificats:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./prod-proxy.conf:/etc/nginx/vhost.d/default_location:ro
      - static-admin:/tmp/static-admin
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - nginx-proxy
    environment:
      ENABLE_IPV6: "true"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_letsencrypt_nginx:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: podverse_letsencrypt_nginx_prod
    depends_on: 
      - podverse_nginx_proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /home/user/tools/nginx_webproxy/certificats:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nginx-proxy
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_db:
    image: postgres:11.5
    container_name: podverse_db_prod
    depends_on:
      - podverse_nginx_proxy
    env_file:
      - ./config/podverse-db-prod.env
    ports:
      - '5432:5432'
    networks:
      - nginx-proxy
    volumes:
      - /mnt/podverse_db_prod_volume:/var/lib/postgresql/data
    command: postgres -c max_connections=200 -c superuser_reserved_connections=20 -c shared_buffers=2GB -c effective_cache_size=6GB -c maintenance_work_mem=512MB -c checkpoint_completion_target=0.7 -c wal_buffers=16MB -c default_statistics_target=100 -c random_page_cost=1.1 -c effective_io_concurrency=200 -c work_mem=5242kB -c min_wal_size=1GB -c max_wal_size=2GB -c max_worker_processes=4 -c max_parallel_workers_per_gather=2 -c max_parallel_workers=4
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_sphinx_search:
    image: macbre/sphinxsearch:3.3.1
    container_name: podverse_sphinx_search_prod
    ports:
      - '9312:9312'
    volumes:
      - ./sphinx:/opt/log
      - ./sphinx:/opt/sphinx/index
      - ./sphinx/sphinx.conf:/opt/sphinx/conf/sphinx.conf
    mem_limit: 512M
    networks:
      - nginx-proxy
    logging:
      driver: 'json-file'
      options:
        max-file: '1'
        max-size: '50m'

  podverse_api:
    image: podverse/podverse_api
    container_name: podverse_api_prod
    depends_on:
      - podverse_nginx_proxy
    env_file:
      - ./config/podverse-api-prod.env
    environment:
      VIRTUAL_HOST:
      VIRTUAL_PORT: 1234
      LETSENCRYPT_HOST:
      LETSENCRYPT_EMAIL:
    expose:
      - 1234
    volumes:
      - ./config/google/jwt.keys.json:/tmp/src/config/google/jwt.keys.json
      - ./config/parser/addFeedUrlsFile.json:/tmp/src/config/parser/addFeedUrlsFile.json
    command: npm start
    networks:
      - nginx-proxy
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_api_parser_worker:
    image: podverse/podverse_api
    container_name: podverse_api_parser_worker_prod
    env_file:
      - ./config/podverse-api-prod.env
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_api_backup_database:
    image: podverse/podverse_api
    container_name: podverse_api_backup_database_prod
    env_file:
      - ./config/podverse-api-prod.env
    volumes:      
      - ../db-backups:/db-backups
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_api_sync_with_podcast_index:
    image: podverse/podverse_api
    container_name: podverse_api_sync_with_podcast_index
    env_file:
      - ./config/podverse-api-prod.env
    volumes:      
      - ../podverse-ops/temp:/temp
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_api_stats:
    image: podverse/podverse_api
    container_name: podverse_api_stats_prod
    env_file:
      - ./config/podverse-api-prod.env
    volumes:
      - ./config/google/jwt.keys.json:/tmp/src/config/google/jwt.keys.json
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_web:
    image: podverse/podverse_web
    container_name: podverse_web_prod
    depends_on:
      - podverse_nginx_proxy
    env_file:
      - ./config/podverse-web-prod.env
    environment:
      VIRTUAL_HOST:
      VIRTUAL_PORT: 8765
      LETSENCRYPT_HOST:
      LETSENCRYPT_EMAIL:
    expose:
      - 8765
    command: npm start
    networks:
      - nginx-proxy
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_admin:
    image: podverse/podverse_admin
    container_name: podverse_admin_prod
    depends_on:
      - podverse_nginx_proxy
    env_file:
      - ./config/podverse-admin-prod.env
    volumes:
      - static-admin:/tmp/static-admin
    environment:
      VIRTUAL_HOST:
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST:
      LETSENCRYPT_EMAIL:
    expose:
      - 8000
    ports:
      - '8000:8000'
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - nginx-proxy
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

networks:
  nginx-proxy:
    external: true

volumes:
  vhost:
  html:
  static-admin:
