version: "2"

services:

  podverse_nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: podverse_nginx_proxy_stage
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  podverse_letsencrypt_nginx:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: podverse_letsencrypt_nginx_stage
    depends_on: 
      - podverse_nginx_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from: 
      - podverse_nginx_proxy

  podverse_db:
    image: postgres
    container_name: podverse_db_stage
    depends_on:
      - podverse_nginx_proxy
      - podverse_letsencrypt_nginx
    env_file:
      - ./config/podverse-db-stage.env
    ports:
      - '5432:5432'

  podverse_api:
    image: podverse/podverse_api
    container_name: podverse_api_stage
    depends_on:
      - podverse_nginx_proxy
      - podverse_letsencrypt_nginx
      - podverse_db
    env_file:
      - ./config/podverse-api-stage.env
    environment:
      VIRTUAL_HOST: api.stage.podverse.fm
      VIRTUAL_PORT: 1234
      LETSENCRYPT_HOST: api.stage.podverse.fm
      LETSENCRYPT_EMAIL:
    expose:
      - 80
      - 1234
    volumes:
      - ./config/google/jwt.keys.json:/tmp/src/config/google/jwt.keys.json
      - ./config/bitpay/api.key:/tmp/src/config/bitpay/api.key
    command: npm start

  podverse_web:
    image: podverse/podverse_web:2.0.0
    container_name: podverse_web_stage
    depends_on:
      - podverse_nginx_proxy
      - podverse_letsencrypt_nginx
      - podverse_db
      - podverse_api
    env_file:
      - ./config/podverse-web-stage.env
    environment:
      VIRTUAL_HOST: stage.podverse.fm
      VIRTUAL_PORT: 8765
      LETSENCRYPT_HOST: stage.podverse.fm
      LETSENCRYPT_EMAIL:
    expose:
      - 80
      - 8765
    command: npm start

networks:
  default:
    external:
      name: nginx-proxy
