version: "3"

services:

  podverse_nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: podverse_nginx_proxy_stage
    ports:
      - 80:80
      - 443:443
    volumes:      
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /home/user/tools/nginx_webproxy/certificats:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./stage-proxy.conf:/etc/nginx/vhost.d/default_location:ro
      - static-admin:/tmp/static-admin
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - nginx-proxy
    environment:
      ENABLE_IPV6: "true"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_letsencrypt_nginx:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: podverse_letsencrypt_nginx_stage
    depends_on: 
      - podverse_nginx_proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /home/user/tools/nginx_webproxy/certificats:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nginx-proxy
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_db:
    image: postgres
    container_name: podverse_db_stage
    depends_on:
      - podverse_nginx_proxy
    env_file:
      - ./config/podverse-db-stage.env
    ports:
      - '5432:5432'
    networks:
      - nginx-proxy
    command: postgres -c max_connections=200 -c superuser_reserved_connections=20 -c shared_buffers=512MB -c effective_cache_size=1536MB -c maintenance_work_mem=128MB -c checkpoint_completion_target=0.7 -c wal_buffers=16MB -c default_statistics_target=100 -c random_page_cost=1.1 -c effective_io_concurrency=200 -c work_mem=1310kB -c min_wal_size=1GB -c max_wal_size=2GB
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_api:
    image: podverse/podverse_api
    container_name: podverse_api_stage
    depends_on:
      - podverse_nginx_proxy
    env_file:
      - ./config/podverse-api-stage.env
    environment:
      VIRTUAL_HOST:
      VIRTUAL_PORT: 1234
      LETSENCRYPT_HOST:
      LETSENCRYPT_EMAIL:
    expose:
      - 80
      - 1234
    volumes:
      - ./config/bitpay/api.key:/tmp/src/config/bitpay/api.key
      - ./config/google/jwt.keys.json:/tmp/src/config/google/jwt.keys.json
    command: npm start
    networks:
      - nginx-proxy
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_api_parser_worker:
    image: podverse/podverse_api
    container_name: podverse_api_parser_worker_stage
    env_file:
      - ./config/podverse-api-stage.env
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_api_stats:
    image: podverse/podverse_api
    container_name: podverse_api_stats_stage
    env_file:
      - ./config/podverse-api-stage.env
    volumes:
      - ./config/google/jwt.keys.json:/tmp/src/config/google/jwt.keys.json
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_web:
    image: podverse/podverse_web
    container_name: podverse_web_stage
    depends_on:
      - podverse_nginx_proxy
    env_file:
      - ./config/podverse-web-stage.env
    environment:
      VIRTUAL_HOST:
      VIRTUAL_PORT: 8765
      LETSENCRYPT_HOST:
      LETSENCRYPT_EMAIL:
    expose:
      - 80
      - 8765
    command: npm start
    networks:
      - nginx-proxy
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_admin:
    image: podverse/podverse_admin
    container_name: podverse_admin_stage
    env_file:
      - ./config/podverse-admin-stage.env
    volumes:
      - static-admin:/tmp/static-admin
    environment:
      VIRTUAL_HOST:
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST:
      LETSENCRYPT_EMAIL:
    expose:
      - 80
      - 8000
    ports:
      - '8000:8000'
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - nginx-proxy
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

networks:
  nginx-proxy:
    external: true

volumes:
  vhost:
  html:
  static-admin:
