version: "2"

volumes:
  db-data: 

services:

  podverse_db_local:
    image: postgres
    env_file:
      - ./config/podverse-db-local.env
    ports:
      - '5432:5432'

  podcast_db_local:
    # image: podverse/podcast_db
    image: podcast_db
    env_file:
      - ./config/podcast-db-local.env
    depends_on:
      - podverse_db_local
    command: npm run migrate

  podcast_db_worker_local:
    image: podverse/podcast_db
    env_file:
      - ./config/podcast-db-local.env
    command: node /tmp/scripts/parseNextFeed.js

  podverse_web_local:
    # image: podverse/podverse-web
    image: podverse_web
    ports: 
      - 8765:8080
    env_file:
      - ./config/podverse-web-local.env
    depends_on: 
      - podcast_db_local
    command: npm run start
  volumes:
    - ./config/googleapi.jwt.keys.json:/tmp/src/services/googleapi/jwt.keys.json

  podverse_db_admin_local:
    # image: podverse/podverse_db_admin
    image: podverse_db_admin
    ports: 
      - 8000:8000
    env_file:
      - ./config/podverse-db-admin-local.env
    depends_on:
      - podverse_db_local
    command: python manage.py runserver 0.0.0.0:8000
