version: "2"

volumes:
  db-data: 

services:

  podverse_db_prod:
    image: postgres
    ports: 
      - '5432:5432'
    env_file:
      - ./config/podverse-db-prod.env
    volumes:
      - db-data:/mnt/podversedbvolume1

  podcast_db_prod:
    image: podverse/podcast_db
    env_file:
      - ./config/podcast-db-prod.env
    depends_on:
      - podverse_db_prod
    command: npm run migrate

  podcast_db_worker_prod:
    image: podverse/podcast_db
    env_file:
      - ./config/podcast-db-prod.env
    command: node /tmp/scripts/parseNextFeed.js

  podverse_web_prod:
    image: podverse/podverse_web
    ports:
      - 8765:8080
    env_file:
      - ./config/podverse-web-prod.env
    depends_on: 
      - podverse_db_prod
    command: npm run start
    volumes:
      - ./config/googleapi.jwt.keys.json:/tmp/src/services/googleapi/jwt.keys.json

  podverse_db_admin_prod:
    image: podverse/podverse_db_admin
    ports: 
      - 8000:8000
    env_file:
      - ./config/podverse-db-admin-prod.env
    depends_on:
      - podverse_db_prod
    command: python manage.py runserver 0.0.0.0:8000