version: "3"

services:

  podverse_nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: podverse_nginx_proxy_prod
    ports:
      - 80:80
      - 443:443
    volumes:      
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /home/user/tools/nginx_webproxy/certificats:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./prod-proxy.conf:/etc/nginx/vhost.d/default_location:ro
      - static-admin:/tmp/static-admin
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - nginx-proxy
    environment:
      ENABLE_IPV6: "true"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_letsencrypt_nginx:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: podverse_letsencrypt_nginx_prod
    depends_on: 
      - podverse_nginx_proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /home/user/tools/nginx_webproxy/certificats:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nginx-proxy
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_api:
    image: podverse/podverse_api
    container_name: podverse_api_prod
    depends_on:
      - podverse_nginx_proxy
    privileged: true
    env_file:
      - ./config/podverse-api-prod.env
    environment:
      VIRTUAL_HOST:
      VIRTUAL_PORT: 1234
      LETSENCRYPT_HOST:
      LETSENCRYPT_EMAIL:
    expose:
      - 1234
    volumes:
      - ./config/google/jwt.keys.json:/tmp/src/config/google/jwt.keys.json
      - ./config/parser/addFeedUrlsFile.json:/tmp/src/config/parser/addFeedUrlsFile.json
    command: npm start
    networks:
      - nginx-proxy
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_api_parser_worker:
    image: podverse/podverse_api
    container_name: podverse_api_parser_worker_prod
    env_file:
      - ./config/podverse-api-prod.env
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_web:
    image: podverse/podverse_web
    container_name: podverse_web_prod
    depends_on:
      - podverse_nginx_proxy
    env_file:
      - ./config/podverse-web-prod.env
    environment:
      VIRTUAL_HOST:
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST:
      LETSENCRYPT_EMAIL:
    expose:
      - 3000
    command: npm start
    networks:
      - nginx-proxy
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

networks:
  nginx-proxy:
    external: true

volumes:
  vhost:
  html:
  static-admin:
