version: "2"

services:

  podverse_db:
    image: postgres
    env_file:
      - ./config/podverse-db.env
    ports:
      - '5432:5432'
    container_name: local_podverse_db

  podverse_api:
    image: podverse_api
    env_file:
      - ./config/podverse-api.env
    depends_on:
      - podverse_db
    ports:
      - '1234:1234'
    volumes:
      - ./config/bitpay/api.key:/tmp/src/config/bitpay/api.key
      - ./config/google/jwt.keys.json:/tmp/src/config/google/jwt.keys.json
    container_name: local_podverse_api
    command: tail -f /dev/null

  podverse_web:
    image: podverse_web
    build: .
    env_file:
      - ./config/podverse-web.env
    depends_on:
      - podverse_db
      - podverse_api
    ports:
      - '8765:8765'
    container_name: local_podverse_web
    command: tail -f /dev/null

networks:
  default:
    driver: bridge
