version: "3"

services:

  podverse_nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: podverse_nginx_proxy_prod
    ports:
      - 80:80
      - 443:443
    volumes:      
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /home/user/tools/nginx_webproxy/certificats:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./prod-proxy.conf:/etc/nginx/vhost.d/default_location:ro
      - static-admin:/tmp/static-admin
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - nginx-proxy
    environment:
      ENABLE_IPV6: "true"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_db:
    image: postgres:11.5
    container_name: podverse_db_prod
    depends_on:
      - podverse_nginx_proxy
    env_file:
      - ./config/podverse-db-prod.env
    ports:
      - '5432:5432'
    networks:
      - nginx-proxy
    volumes:
      - /mnt/podverse_db_prod_volume:/var/lib/postgresql/data
    command: postgres -c max_connections=200 -c superuser_reserved_connections=20 -c shared_buffers=2GB -c effective_cache_size=6GB -c maintenance_work_mem=512MB -c checkpoint_completion_target=0.7 -c wal_buffers=16MB -c default_statistics_target=100 -c random_page_cost=1.1 -c effective_io_concurrency=200 -c work_mem=5242kB -c min_wal_size=1GB -c max_wal_size=2GB -c max_worker_processes=4 -c max_parallel_workers_per_gather=2 -c max_parallel_workers=4
    restart: always
    shm_size: 1gb
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_manticore:
    image: manticoresearch/manticore
    container_name: podverse_manticore_prod
    depends_on: 
      - podverse_db
    restart: always
    networks:
      - nginx-proxy
    ports:
      - 9306:9306
      - 9308:9308
    ulimits:
      nproc: 65535
      nofile:
         soft: 65535
         hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./manticore/data:/var/lib/manticore
      - ./manticore/episode_export_csvs/episode_export_00.csv:/etc/manticoresearch/episode_export_00.csv
      - ./manticore/episode_export_csvs/episode_export_01.csv:/etc/manticoresearch/episode_export_01.csv
      - ./manticore/episode_export_csvs/episode_export_02.csv:/etc/manticoresearch/episode_export_02.csv
      - ./manticore/episode_export_csvs/episode_export_03.csv:/etc/manticoresearch/episode_export_03.csv
      - ./manticore/episode_export_csvs/episode_export_04.csv:/etc/manticoresearch/episode_export_04.csv
      - ./manticore/episode_export_csvs/episode_export_05.csv:/etc/manticoresearch/episode_export_05.csv
      - ./manticore/episode_export_csvs/episode_export_06.csv:/etc/manticoresearch/episode_export_06.csv
      - ./manticore/episode_export_csvs/episode_export_07.csv:/etc/manticoresearch/episode_export_07.csv
      - ./manticore/episode_export_csvs/episode_export_08.csv:/etc/manticoresearch/episode_export_08.csv
      - ./manticore/episode_export_csvs/episode_export_09.csv:/etc/manticoresearch/episode_export_09.csv
      - ./manticore/episode_export_csvs/episode_export_10.csv:/etc/manticoresearch/episode_export_10.csv
      - ./manticore/episode_export_csvs/episode_export_11.csv:/etc/manticoresearch/episode_export_11.csv
      - ./manticore/episode_export_csvs/episode_export_12.csv:/etc/manticoresearch/episode_export_12.csv
      - ./manticore/episode_export_csvs/episode_export_13.csv:/etc/manticoresearch/episode_export_13.csv
      - ./manticore/episode_export_csvs/episode_export_14.csv:/etc/manticoresearch/episode_export_14.csv
      - ./manticore/episode_export_csvs/episode_export_15.csv:/etc/manticoresearch/episode_export_15.csv
      - ./manticore/episode_export_csvs/episode_export_16.csv:/etc/manticoresearch/episode_export_16.csv
      - ./manticore/episode_export_csvs/episode_export_17.csv:/etc/manticoresearch/episode_export_17.csv
      - ./manticore/episode_export_csvs/episode_export_18.csv:/etc/manticoresearch/episode_export_18.csv
      - ./manticore/episode_export_csvs/episode_export_19.csv:/etc/manticoresearch/episode_export_19.csv
      - ./manticore/episode_export_csvs/episode_export_20.csv:/etc/manticoresearch/episode_export_20.csv
      - ./manticore/episode_export_csvs/episode_export_21.csv:/etc/manticoresearch/episode_export_21.csv
      - ./manticore/episode_export_csvs/episode_export_22.csv:/etc/manticoresearch/episode_export_22.csv
      - ./manticore/episode_export_csvs/episode_export_23.csv:/etc/manticoresearch/episode_export_23.csv
      - ./manticore/episode_export_csvs/episode_export_24.csv:/etc/manticoresearch/episode_export_24.csv
      - ./manticore/episode_export_csvs/episode_export_25.csv:/etc/manticoresearch/episode_export_25.csv
      - ./manticore/episode_export_csvs/episode_export_26.csv:/etc/manticoresearch/episode_export_26.csv
      - ./manticore/episode_export_csvs/episode_export_27.csv:/etc/manticoresearch/episode_export_27.csv
      - ./manticore/episode_export_csvs/episode_export_28.csv:/etc/manticoresearch/episode_export_28.csv
      - ./manticore/episode_export_csvs/episode_export_29.csv:/etc/manticoresearch/episode_export_29.csv
      - ./manticore/episode_export_csvs/episode_export_30.csv:/etc/manticoresearch/episode_export_30.csv
      - ./manticore/episode_export_csvs/episode_export_31.csv:/etc/manticoresearch/episode_export_31.csv
      - ./manticore/episode_export_csvs/episode_export_32.csv:/etc/manticoresearch/episode_export_32.csv
      - ./manticore/episode_export_csvs/episode_export_33.csv:/etc/manticoresearch/episode_export_33.csv
      - ./manticore/episode_export_csvs/episode_export_34.csv:/etc/manticoresearch/episode_export_34.csv
      - ./manticore/episode_export_csvs/episode_export_35.csv:/etc/manticoresearch/episode_export_35.csv
      - ./manticore/episode_export_csvs/episode_export_36.csv:/etc/manticoresearch/episode_export_36.csv
      - ./manticore/episode_export_csvs/episode_export_37.csv:/etc/manticoresearch/episode_export_37.csv
      - ./manticore/episode_export_csvs/episode_export_38.csv:/etc/manticoresearch/episode_export_38.csv
      - ./manticore/episode_export_csvs/episode_export_39.csv:/etc/manticoresearch/episode_export_39.csv
      - ./manticore/episode_export_csvs/episode_export_40.csv:/etc/manticoresearch/episode_export_40.csv
      - ./manticore/episode_export_csvs/episode_export_41.csv:/etc/manticoresearch/episode_export_41.csv
      - ./manticore/episode_export_csvs/episode_export_42.csv:/etc/manticoresearch/episode_export_42.csv
      - ./manticore/episode_export_csvs/episode_export_43.csv:/etc/manticoresearch/episode_export_43.csv
      - ./manticore/episode_export_csvs/episode_export_44.csv:/etc/manticoresearch/episode_export_44.csv
      - ./manticore/episode_export_csvs/episode_export_45.csv:/etc/manticoresearch/episode_export_45.csv
      - ./manticore/episode_export_csvs/episode_export_46.csv:/etc/manticoresearch/episode_export_46.csv
      - ./manticore/episode_export_csvs/episode_export_47.csv:/etc/manticoresearch/episode_export_47.csv
      - ./manticore/episode_export_csvs/episode_export_48.csv:/etc/manticoresearch/episode_export_48.csv
      - ./manticore/episode_export_csvs/episode_export_49.csv:/etc/manticoresearch/episode_export_49.csv
      - ./manticore/episode_export_csvs/episode_export_50.csv:/etc/manticoresearch/episode_export_50.csv
      - ./manticore/episode_export_csvs/episode_export_51.csv:/etc/manticoresearch/episode_export_51.csv
      - ./manticore/episode_export_csvs/episode_export_52.csv:/etc/manticoresearch/episode_export_52.csv
      - ./manticore/episode_export_csvs/episode_export_53.csv:/etc/manticoresearch/episode_export_53.csv
      - ./manticore/episode_export_csvs/episode_export_54.csv:/etc/manticoresearch/episode_export_54.csv
      - ./manticore/episode_export_csvs/episode_export_55.csv:/etc/manticoresearch/episode_export_55.csv
      - ./manticore/episode_export_csvs/episode_export_56.csv:/etc/manticoresearch/episode_export_56.csv
      - ./manticore/episode_export_csvs/episode_export_57.csv:/etc/manticoresearch/episode_export_57.csv
      - ./manticore/episode_export_csvs/episode_export_58.csv:/etc/manticoresearch/episode_export_58.csv
      - ./manticore/episode_export_csvs/episode_export_59.csv:/etc/manticoresearch/episode_export_59.csv
      - ./manticore/episode_export_csvs/episode_export_60.csv:/etc/manticoresearch/episode_export_60.csv
      - ./manticore/episode_export_csvs/episode_export_61.csv:/etc/manticoresearch/episode_export_61.csv
      - ./manticore/episode_export_csvs/episode_export_62.csv:/etc/manticoresearch/episode_export_62.csv
      - ./manticore/episode_export_csvs/episode_export_63.csv:/etc/manticoresearch/episode_export_63.csv
      - ./manticore/episode_export_csvs/episode_export_64.csv:/etc/manticoresearch/episode_export_64.csv
      - ./manticore/episode_export_csvs/episode_export_65.csv:/etc/manticoresearch/episode_export_65.csv
      - ./manticore/episode_export_csvs/episode_export_66.csv:/etc/manticoresearch/episode_export_66.csv
      - ./manticore/episode_export_csvs/episode_export_67.csv:/etc/manticoresearch/episode_export_67.csv
      - ./manticore/episode_export_csvs/episode_export_68.csv:/etc/manticoresearch/episode_export_68.csv
      - ./manticore/episode_export_csvs/episode_export_69.csv:/etc/manticoresearch/episode_export_69.csv
      - ./manticore/episode_export_csvs/episode_export_70.csv:/etc/manticoresearch/episode_export_70.csv
      - ./manticore/episode_export_csvs/episode_export_71.csv:/etc/manticoresearch/episode_export_71.csv
      - ./manticore/episode_export_csvs/episode_export_72.csv:/etc/manticoresearch/episode_export_72.csv
      - ./manticore/episode_export_csvs/episode_export_73.csv:/etc/manticoresearch/episode_export_73.csv
      - ./manticore/episode_export_csvs/episode_export_74.csv:/etc/manticoresearch/episode_export_74.csv
      - ./manticore/episode_export_csvs/episode_export_75.csv:/etc/manticoresearch/episode_export_75.csv
      - ./manticore/episode_export_csvs/episode_export_76.csv:/etc/manticoresearch/episode_export_76.csv
      - ./manticore/episode_export_csvs/episode_export_77.csv:/etc/manticoresearch/episode_export_77.csv
      - ./manticore/episode_export_csvs/episode_export_78.csv:/etc/manticoresearch/episode_export_78.csv
      - ./manticore/episode_export_csvs/episode_export_79.csv:/etc/manticoresearch/episode_export_79.csv
      - ./manticore/episode_export_csvs/episode_export_80.csv:/etc/manticoresearch/episode_export_80.csv
      - ./manticore/episode_export_csvs/episode_export_81.csv:/etc/manticoresearch/episode_export_81.csv
      - ./manticore/episode_export_csvs/episode_export_82.csv:/etc/manticoresearch/episode_export_82.csv
      - ./manticore/episode_export_csvs/episode_export_83.csv:/etc/manticoresearch/episode_export_83.csv
      - ./manticore/episode_export_csvs/episode_export_84.csv:/etc/manticoresearch/episode_export_84.csv
      - ./manticore/episode_export_csvs/episode_export_85.csv:/etc/manticoresearch/episode_export_85.csv
      - ./manticore/episode_export_csvs/episode_export_86.csv:/etc/manticoresearch/episode_export_86.csv
      - ./manticore/episode_export_csvs/episode_export_87.csv:/etc/manticoresearch/episode_export_87.csv
      - ./manticore/episode_export_csvs/episode_export_88.csv:/etc/manticoresearch/episode_export_88.csv
      - ./manticore/episode_export_csvs/episode_export_89.csv:/etc/manticoresearch/episode_export_89.csv
      - ./manticore/episode_export_csvs/episode_export_90.csv:/etc/manticoresearch/episode_export_90.csv
      - ./manticore/episode_export_csvs/episode_export_91.csv:/etc/manticoresearch/episode_export_91.csv
      - ./manticore/episode_export_csvs/episode_export_92.csv:/etc/manticoresearch/episode_export_92.csv
      - ./manticore/episode_export_csvs/episode_export_93.csv:/etc/manticoresearch/episode_export_93.csv
      - ./manticore/episode_export_csvs/episode_export_94.csv:/etc/manticoresearch/episode_export_94.csv
      - ./manticore/episode_export_csvs/episode_export_95.csv:/etc/manticoresearch/episode_export_95.csv
      - ./manticore/episode_export_csvs/episode_export_96.csv:/etc/manticoresearch/episode_export_96.csv
      - ./manticore/episode_export_csvs/episode_export_97.csv:/etc/manticoresearch/episode_export_97.csv
      - ./manticore/episode_export_csvs/episode_export_98.csv:/etc/manticoresearch/episode_export_98.csv
      - ./manticore/episode_export_csvs/episode_export_99.csv:/etc/manticoresearch/episode_export_99.csv
      - ./manticore/manticore.conf:/etc/manticoresearch/manticore.conf
    logging:
      driver: 'json-file'
      options:
        max-file: '1'
        max-size: '50m'

  podverse_api_backup_database:
    image: podverse/podverse_api
    container_name: podverse_api_backup_database_prod
    env_file:
      - ./config/podverse-api-prod.env
    volumes:      
      - ../db-backups:/db-backups
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_api_sync_with_podcast_index:
    image: podverse/podverse_api
    container_name: podverse_api_sync_with_podcast_index
    env_file:
      - ./config/podverse-api-prod.env
    volumes:      
      - ../podverse-ops/temp:/temp
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

networks:
  nginx-proxy:
    external: true

volumes:
  vhost:
  html:
  static-admin:
